name: Deploy Website

on:
    push:
        branches: [ production ] 

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Deploy via SSH
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  key: ${{ secrets.SSH_KEY }}
                  port: 22
                  script: |
                     cd /var/www/dcote.net
                     git pull origin production
                     
                     docker compose -f docker-compose.prod.yml build --pull
                     
                     docker compose -f docker-compose.prod.yml up -d
                     
                     docker compose -f docker-compose.prod.yml exec -T app php artisan migrate --force
                     docker compose -f docker-compose.prod.yml exec -T app php artisan config:cache
                     docker compose -f docker-compose.prod.yml exec -T app php artisan route:cache
                     docker compose -f docker-compose.prod.yml exec -T app php artisan view:cache
