name: Deploy Website

on:
  push:
    branches: [ production ] 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd /var/www/dcote-site-main
            git pull origin production
            
            # Установка зависимостей
            composer install --no-dev --optimize-autoloader
            
            # Настройка Laravel (миграции, кеш)
            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
